<script lang="ts">import {onMount} from 'svelte';import AppShell from '$lib/components/AppShell.svelte';import PageHeader from '$lib/components/PageHeader.svelte';import AdminStatCard from '$lib/components/AdminStatCard.svelte';import AdminSection from '$lib/components/AdminSection.svelte';import StatusBadge from '$lib/components/StatusBadge.svelte';import {currentUser} from '$lib/stores/user';import {fetchAdminOverview, type AdminOverview} from '$lib/api';import { getErrorMessage } from '$lib/errors';let data:AdminOverview|null=null;let loading=false;let error='';const load=async()=>{loading=true;error='';try{data=await fetchAdminOverview();}catch(error:unknown){error=getErrorMessage(error,'Erreur');}finally{loading=false;}};onMount(load);</script>
<AppShell>{#if $currentUser?.role!=='admin'}<p>Accès restreint</p>{:else}<PageHeader title="Admin Overview" subtitle="Cockpit SaaS"/><button on:click={load}>Refresh</button>{#if loading}<p>Chargement…</p>{/if}{#if error}<p>{error}</p>{/if}
{#if data}<AdminSection title="Utilisateurs"><div class="g"><AdminStatCard label="Total" value={String(data?.users?.total??0)}/><AdminStatCard label="Verified" value={String(data?.users?.verified??0)}/><AdminStatCard label="Admins" value={String(data?.users?.admins??0)}/></div></AdminSection>
<AdminSection title="Plans"><div class="g"><AdminStatCard label="Free" value={String(data?.plans?.free??0)}/><AdminStatCard label="Pro" value={String(data?.plans?.pro??0)}/><AdminStatCard label="Studio" value={String(data?.plans?.studio??0)}/></div></AdminSection>
<AdminSection title="Abonnements"><div class="g"><AdminStatCard label="Total" value={String(data?.subscriptions?.total??0)}/><AdminStatCard label="Active" value={String(data?.subscriptions?.active??0)}/><AdminStatCard label="Inactive" value={String(data?.subscriptions?.inactive??0)}/></div></AdminSection>
<AdminSection title="Alertes"><div class="g"><AdminStatCard label="Rules enabled" value={String(data?.alerts?.rules_enabled??0)}/><AdminStatCard label="Sent 24h" value={String(data?.alerts?.deliveries_sent_24h??0)}/><AdminStatCard label="Failed 24h" value={String(data?.alerts?.deliveries_failed_24h??0)}/><AdminStatCard label="Skipped 24h" value={String(data?.alerts?.deliveries_skipped_24h??0)}/></div></AdminSection>
<AdminSection title="Rapports"><div class="g"><AdminStatCard label="Pending" value={String(data?.reports?.pending??0)}/><AdminStatCard label="Completed 24h" value={String(data?.reports?.completed_24h??0)}/><AdminStatCard label="Failed 24h" value={String(data?.reports?.failed_24h??0)}/></div></AdminSection>
<AdminSection title="Notifications"><div class="g"><AdminStatCard label="Total" value={String(data?.notifications?.total??0)}/><AdminStatCard label="Unread" value={String(data?.notifications?.unread??0)}/></div></AdminSection>
<AdminSection title="Emails"><div class="g"><AdminStatCard label="Sent 24h" value={String(data?.emails?.sent_24h??0)}/><AdminStatCard label="Failed 24h" value={String(data?.emails?.failed_24h??0)}/><AdminStatCard label="Skipped 24h" value={String(data?.emails?.skipped_24h??0)}/></div></AdminSection>
<AdminSection title="Sources"><p>YouTube <StatusBadge status={data?.sources?.youtube??'unknown'}/></p><p>TikTok <StatusBadge status={data?.sources?.tiktok??'unknown'}/></p><p>Instagram <StatusBadge status={data?.sources?.instagram??'unknown'}/></p></AdminSection>{/if}{/if}</AppShell>
<style>.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.6rem}</style>
