#!/usr/bin/env bash
set -euo pipefail

REQUIRE_MONITORING_RUNNING="${REQUIRE_MONITORING_RUNNING:-0}"
CURL_IMAGE="${CURL_IMAGE:-curlimages/curl:8.10.1}"

fail() {
  echo "❌ $1"
  exit 1
}

info() {
  echo "ℹ️  $1"
}

success() {
  echo "✅ $1"
}

require_file() {
  [ -f "$1" ] || fail "Missing required file: $1"
}

compose() {
  docker compose --env-file .env.production -f docker-compose.prod.yml -f docker-compose.monitoring.yml "$@"
}

check_prerequisites() {
  require_file .env.production
  require_file docker-compose.monitoring.yml
  compose config >/dev/null
}

send_test_alert() {
  docker run --rm --network container:trend-scope-alertmanager "$CURL_IMAGE" -fsS \
    -H "Content-Type: application/json" \
    -XPOST http://localhost:9093/api/v2/alerts \
    -d '[
      {
        "labels": {
          "alertname": "TrendScopeManualAlertTest",
          "severity": "info",
          "source": "prod-alerting-test"
        },
        "annotations": {
          "summary": "Manual Alertmanager test",
          "description": "This is a manual test alert generated by prod-alerting-test.sh"
        }
      }
    ]' >/dev/null

  docker run --rm --network container:trend-scope-alertmanager "$CURL_IMAGE" -fsS \
    http://localhost:9093/api/v2/alerts >/dev/null
}

main() {
  check_prerequisites

  if [ "$REQUIRE_MONITORING_RUNNING" = "0" ]; then
    info "REQUIRE_MONITORING_RUNNING=0, skipping Alertmanager test alert"
    success "Alerting test prerequisites look valid"
    exit 0
  fi

  info "REQUIRE_MONITORING_RUNNING=1, sending manual test alert to Alertmanager"
  send_test_alert
  success "Alertmanager test alert sent and endpoint verified"
}

main "$@"
